config/routes.rb
Rails.application.routes.draw do

  root to: 'pages#home'

  get '/about', to: "pages#about"
  get '/contact', to: "pages#contact"
  get '/booking', to: "pages#booking"
  get '/music', to: "pages#music"
  get '/photography', to: "pages#photography"
  get '/home', to: "pages#home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

  def contact
  end

  def booking
  end

end

app/controllers/photography_controller.rb
class PhotographyController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photography_helper.rb
module PhotographyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ogazon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/booking.html.erb
<h1>Booking form</h1>

app/views/pages/home.html.erb
<div class="background-home">
<h1>OGAZÓN</h1>
</div>

app/views/pages/xxxxx.html.erb
HOME
<div class="banner" style="background-image: asset_url('muro1.jpeg'); linear-gradient(rgba(0,0,0,0.0),rgba(0,0,0,0.4))">
    <h1 >OGAZÓN</h1>
</div>
 <div class="links d-flex justify-content-between">
    <%= link_to "Music", music_path %>
    <%= link_to "Photography", photography_path %>
    <%= link_to "Biography", about_path %>
    <%= link_to "Contact", contact_path %>
    <%= link_to "Book", booking_path %>
  </div>

CONTACT

 <div class="banner-bio box" style="background-image: asset_url('Oggy_presspic.jpg'); linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))">
  <div class="flex flex-col sm:w-1/3 items-center space-y-2 px-6 p1ym4qhs flex flex-col items-center space-y-2 px-6">
  <nav aria-label="...">
  <div class="pager">
    <div class="back" ><%= link_to "Back", home_path %><span aria-hidden="true"> </span></div>
</div>
<div class=container>
   <h1>Booking information</h1>
<p> E-mail </p>
</div>

ABOUT

<div class="banner-bio box" style="background-image: asset_url('Oggy_presspic.jpg'); linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4))">
  <div class="flex flex-col sm:w-1/3 items-center space-y-2 px-6 p1ym4qhs flex flex-col items-center space-y-2 px-6">
  <nav aria-label="...">
    <div class="back" ><%= link_to "Back", home_path %><span aria-hidden="true">&larr;</span> </div>

  </div>
</nav>
    <h1 class="text-center" style="font-size:70px; margin-bottom: 30px; margin-top: 100px;"> OGAZÓN BIOGRAPHY</h1>
      <p class="text-center"> The part-Spanish, part-Luxembourgish artist has cultivated her skill and selection process in Amsterdam’s after-hour scene. Now residing in Berlin, her rhythms find inspiration in the eclectic and somewhat wilder characteristics of the city. Not bound to a sound in particular, Ogazón is best in arranging a coherent thread of feelings throughout her sets, be it melancholic bliss, ecstatic hope or just pure dancefloor pleasure.</p>
</div>

 <div class="d-flex justify-content-between" style="font-size:40px; font-colour:black">
    <%= link_to "Instagram", "https://www.instagram.com/ogazon.wav/" %>
    <%= link_to "SoundCloud", "https://soundcloud.com/ogazon" %>
    <%= link_to "Resident Advisor", "https://ra.co/dj/ogazon" %>
    <%= link_to "Facebook", "https://www.facebook.com/ogazon.music/" %>

  </div>